#!/bin/bash

cd "$(dirname $0)"
export LC_ALL=C
export WINEBUILD_DIR="$PWD"
source "$WINEBUILD_DIR/lib/sources"

[ -e $BUILD_LOCK ] && echo "Already running, exiting" && exit
touch $BUILD_LOCK
notify "[Winebuild] Winebuild is starting !"

# Get target from POL... linux-x86/darwin-x86/freebsd-x86/linux-amd64
POL_Start_Winebuild "$1"

rm $BUILD_LOCK

exit 0 
